/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JInternalFrame;

/**
 *
 * @author adam
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Entidades = new javax.swing.JMenu();
        jmColectivos = new javax.swing.JMenuItem();
        jmPasajeros = new javax.swing.JMenuItem();
        jmRutas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmPasajes = new javax.swing.JMenuItem();
        jmHorariosDeRutas = new javax.swing.JMenuItem();
        jmHorarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1548, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        Entidades.setText("Datos");

        jmColectivos.setText("Colectivos");
        jmColectivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmColectivosActionPerformed(evt);
            }
        });
        Entidades.add(jmColectivos);

        jmPasajeros.setText("Pasajeros");
        jmPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPasajerosActionPerformed(evt);
            }
        });
        Entidades.add(jmPasajeros);

        jmRutas.setText("Rutas");
        jmRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRutasActionPerformed(evt);
            }
        });
        Entidades.add(jmRutas);

        jMenuBar1.add(Entidades);

        jMenu1.setText("Relaciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmPasajes.setText("Pasajes");
        jmPasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPasajesActionPerformed(evt);
            }
        });
        jMenu1.add(jmPasajes);

        jmHorariosDeRutas.setText("Horarios de rutas");
        jmHorariosDeRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHorariosDeRutasActionPerformed(evt);
            }
        });
        jMenu1.add(jmHorariosDeRutas);

        jmHorarios.setText("Horarios");
        jmHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHorariosActionPerformed(evt);
            }
        });
        jMenu1.add(jmHorarios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmColectivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmColectivosActionPerformed
        Colectivos colectivos = new Colectivos();
        dibujarVentana(colectivos);
    }//GEN-LAST:event_jmColectivosActionPerformed

    private void jmHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHorariosActionPerformed
        Horarios horarios = new Horarios();
        dibujarVentana(horarios);
    }//GEN-LAST:event_jmHorariosActionPerformed

    private void jmPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPasajesActionPerformed
        Pasajes pasajes = new Pasajes();
        dibujarVentana(pasajes);
    }//GEN-LAST:event_jmPasajesActionPerformed

    private void jmPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPasajerosActionPerformed
        Pasajeros pasajeros = new Pasajeros();
        dibujarVentana(pasajeros);
    }//GEN-LAST:event_jmPasajerosActionPerformed

    private void jmRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRutasActionPerformed
        Rutas rutas = new Rutas();
        dibujarVentana(rutas);
    }//GEN-LAST:event_jmRutasActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmHorariosDeRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHorariosDeRutasActionPerformed
        HorariosDeRutas horariosDeRutas = new HorariosDeRutas();
        dibujarVentana(horariosDeRutas);
    }//GEN-LAST:event_jmHorariosDeRutasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    private void dibujarVentana(JInternalFrame ventana) {
        escritorio.removeAll();
        escritorio.repaint();
        ventana.setVisible(true);
        escritorio.add(ventana);
        escritorio.moveToFront(ventana);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Entidades;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmColectivos;
    private javax.swing.JMenuItem jmHorarios;
    private javax.swing.JMenuItem jmHorariosDeRutas;
    private javax.swing.JMenuItem jmPasajeros;
    private javax.swing.JMenuItem jmPasajes;
    private javax.swing.JMenuItem jmRutas;
    // End of variables declaration//GEN-END:variables
}
