package vistas.jtabla;

import java.util.Arrays;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class ReprogramarPasaje extends javax.swing.JFrame {

    private JTablaCompuesta tabla;
    private ModeloTablaCompuesta modelo;

    /**
     * Creates new form MainFrame
     */
    public ReprogramarPasaje() {
        initComponents();
        customizeComponents();
        addRowSelectionListener();
    }

    private void customizeComponents() {
        // Crear el modelo de la tabla
        modelo = new ModeloTablaCompuesta();

        // Secciones y datos de ejemplo
        SeccionTabla datosPersonales = new SeccionTabla("Datos Pasajero", "Pasajeros");
        datosPersonales.agregarColumna(new FormularioData("DNI", "txt", true));
        datosPersonales.agregarColumna(new FormularioData("Nombre", "txt", true));
        datosPersonales.agregarColumna(new FormularioData("Apellido", "txt", true));
        datosPersonales.agregarFila(1, new Object[]{1001, "Juan", "Pérez"});
        datosPersonales.agregarFila(2, new Object[]{1002, "María", "Gómez"});

        SeccionTabla orgRol = new SeccionTabla("Pasajes Disponibles", "Pasajes");
        orgRol.agregarColumna(new FormularioData("Fecha del Viaje",
                Arrays.asList("2024-6-17", "2024-6-18", "2024-6-19")));
        orgRol.agregarColumna(new FormularioData("Horario", Arrays.asList("09:00hs", "11:15hs", "13:30hs")));
        orgRol.agregarFila(1, new Object[]{"2024-6-17", "09:00hs"});
        orgRol.agregarFila(2, new Object[]{"2024-6-18", "11:15hs"});

        modelo.agregarSeccion(datosPersonales);
        modelo.agregarSeccion(orgRol);

        // Populate combo boxes
        for (Object fecha : orgRol.getColumnasConfiguracion().get(0).getValoresComboBox()) {
            comboFecha.addItem(fecha.toString());
        }
        for (Object horario : orgRol.getColumnasConfiguracion().get(1).getValoresComboBox()) {
            comboHorario.addItem(horario.toString());
        }

        // Crear la tabla personalizada
        tabla = new JTablaCompuesta(modelo);
        jScrollPane1.setViewportView(tabla);  // Add the custom table to the scroll pane

        // Set up the form fields
        setupFormFields(datosPersonales, orgRol);
    }

    private void setupFormFields(SeccionTabla... secciones) {
        for (SeccionTabla seccion : secciones) {
            Object[] campos = new Object[seccion.getNombresColumnas().size()];
            JPanel panel = seccion.getNombreSeccion().equals("Sección 1") ? panelCamposTexto1 : panelCamposTexto2;
            tabla.agregarCamposSeccion(panel, seccion, campos);
        }
    }

    // Add row selection listener
    private void addRowSelectionListener() {
        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tabla.getSelectedRow();
                    if (selectedRow != -1) {
                        updateFormFields(selectedRow);
                    }
                }
            }
        });
    }

    // Update form fields based on selected row
    private void updateFormFields(int selectedRow) {
        // Datos Pasajero section
        txtDni.setText(tabla.getValueAt(selectedRow, 0).toString());
        txtNombre.setText(tabla.getValueAt(selectedRow, 1).toString());
        txtApellido.setText(tabla.getValueAt(selectedRow, 2).toString());

        // Pasajes Disponibles section
        String fechaSeleccionada = tabla.getValueAt(selectedRow, 3).toString();
        String horarioSeleccionado = tabla.getValueAt(selectedRow, 4).toString();

        // Update combo boxes
        comboFecha.setSelectedItem(fechaSeleccionada);
        comboHorario.setSelectedItem(horarioSeleccionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelCamposTexto1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        panelCamposTexto2 = new javax.swing.JPanel();
        comboFecha = new javax.swing.JComboBox<>();
        comboHorario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblNombre.setText("Nombres:");

        jLabel1.setText("Apellidos:");

        lblDni.setText("DNI:");

        javax.swing.GroupLayout panelCamposTexto1Layout = new javax.swing.GroupLayout(panelCamposTexto1);
        panelCamposTexto1.setLayout(panelCamposTexto1Layout);
        panelCamposTexto1Layout.setHorizontalGroup(
            panelCamposTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCamposTexto1Layout.setVerticalGroup(
            panelCamposTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposTexto1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposTexto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCamposTexto2Layout = new javax.swing.GroupLayout(panelCamposTexto2);
        panelCamposTexto2.setLayout(panelCamposTexto2Layout);
        panelCamposTexto2Layout.setHorizontalGroup(
            panelCamposTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposTexto2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        panelCamposTexto2Layout.setVerticalGroup(
            panelCamposTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposTexto2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelCamposTexto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelCamposTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelCamposTexto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(panelCamposTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelCamposTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReprogramarPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReprogramarPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReprogramarPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReprogramarPasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReprogramarPasaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFecha;
    private javax.swing.JComboBox<String> comboHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelCamposTexto1;
    private javax.swing.JPanel panelCamposTexto2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
