/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.jpanel;

/**
 *
 * @author adam
 */
public class DatosHorarios extends javax.swing.JPanel {

    /**
     * Creates new form DatosHorarios
     */
    public DatosHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHorarios = new javax.swing.JPanel();
        panelHoraLlegada = new javax.swing.JPanel();
        lblHoraLlegada = new javax.swing.JLabel();
        comboHoraLlegada = new javax.swing.JComboBox<>();
        lblIdHorario = new javax.swing.JLabel();
        checkboxHorariosActivos = new javax.swing.JCheckBox();
        txtIdHorario = new javax.swing.JTextField();
        panelHoraSalida = new javax.swing.JPanel();
        lblHoraSalida = new javax.swing.JLabel();
        comboHoraSalida = new javax.swing.JComboBox<>();
        lblHorarios = new javax.swing.JLabel();

        panelHorarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblHoraLlegada.setText("Hora llegada");

        javax.swing.GroupLayout panelHoraLlegadaLayout = new javax.swing.GroupLayout(panelHoraLlegada);
        panelHoraLlegada.setLayout(panelHoraLlegadaLayout);
        panelHoraLlegadaLayout.setHorizontalGroup(
            panelHoraLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoraLlegadaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHoraLlegada)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(panelHoraLlegadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboHoraLlegada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHoraLlegadaLayout.setVerticalGroup(
            panelHoraLlegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoraLlegadaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHoraLlegada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        lblIdHorario.setText("idHorario");

        checkboxHorariosActivos.setText("Horarios Activos");
        checkboxHorariosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxHorariosActivosActionPerformed(evt);
            }
        });

        txtIdHorario.setEnabled(false);

        lblHoraSalida.setText("Hora salida");

        javax.swing.GroupLayout panelHoraSalidaLayout = new javax.swing.GroupLayout(panelHoraSalida);
        panelHoraSalida.setLayout(panelHoraSalidaLayout);
        panelHoraSalidaLayout.setHorizontalGroup(
            panelHoraSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoraSalidaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHoraSalida)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(panelHoraSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboHoraSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHoraSalidaLayout.setVerticalGroup(
            panelHoraSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoraSalidaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblHoraSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        lblHorarios.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblHorarios.setText("Horarios");

        javax.swing.GroupLayout panelHorariosLayout = new javax.swing.GroupLayout(panelHorarios);
        panelHorarios.setLayout(panelHorariosLayout);
        panelHorariosLayout.setHorizontalGroup(
            panelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHorariosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHorariosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxHorariosActivos))
                    .addGroup(panelHorariosLayout.createSequentialGroup()
                        .addComponent(panelHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelHorariosLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblHorarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHorariosLayout.setVerticalGroup(
            panelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHorariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHorarios)
                .addGap(8, 8, 8)
                .addGroup(panelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdHorario)
                    .addComponent(txtIdHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxHorariosActivos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxHorariosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxHorariosActivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxHorariosActivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkboxHorariosActivos;
    private javax.swing.JComboBox<String> comboHoraLlegada;
    private javax.swing.JComboBox<String> comboHoraSalida;
    private javax.swing.JLabel lblHoraLlegada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblIdHorario;
    private javax.swing.JPanel panelHoraLlegada;
    private javax.swing.JPanel panelHoraSalida;
    private javax.swing.JPanel panelHorarios;
    private javax.swing.JTextField txtIdHorario;
    // End of variables declaration//GEN-END:variables
}
