package vistas.entregaFinal;

import java.awt.Color;

/**
 *
 * @author adam, enzo, alexis, nicolas
 */
public class CargaDePasajero extends javax.swing.JPanel {

    /**
     * Creates new form CargaDePasajero
     */
    public CargaDePasajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLDNI = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLCorreo = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jTDNI = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTCorreo = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jLCargaPasajero = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(817, 472));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        jLDNI.setForeground(new java.awt.Color(102, 102, 102));
        jLDNI.setText("DNI");

        jLNombre.setForeground(new java.awt.Color(102, 102, 102));
        jLNombre.setText("Nombre");

        jLApellido.setForeground(new java.awt.Color(102, 102, 102));
        jLApellido.setText("Apellido");

        jLCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jLCorreo.setText("Correo");

        jLTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jLTelefono.setText("Telefono");

        jBGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jBGuardar.setForeground(new java.awt.Color(102, 102, 102));
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jBGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBGuardarMouseExited(evt);
            }
        });

        jBLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jBLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jBLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLimpiarMouseExited(evt);
            }
        });

        jTDNI.setBackground(new java.awt.Color(255, 255, 255));
        jTDNI.setForeground(new java.awt.Color(153, 153, 153));
        jTDNI.setText("Ingrese su DNI");
        jTDNI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        jTDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTDNIMousePressed(evt);
            }
        });
        jTDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTDNIKeyTyped(evt);
            }
        });

        jTNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTNombre.setText("Ingrese su nombre");
        jTNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        jTNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTNombreMousePressed(evt);
            }
        });

        jTApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTApellido.setForeground(new java.awt.Color(153, 153, 153));
        jTApellido.setText("Ingrese su apellido");
        jTApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        jTApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTApellidoMousePressed(evt);
            }
        });

        jTCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jTCorreo.setForeground(new java.awt.Color(153, 153, 153));
        jTCorreo.setText("Ingrese su correo electronico");
        jTCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        jTCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTCorreoMousePressed(evt);
            }
        });

        jTTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jTTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jTTelefono.setText("Ingrese el numero de su telefono");
        jTTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        jTTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTTelefonoMousePressed(evt);
            }
        });
        jTTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTelefonoKeyTyped(evt);
            }
        });

        jLCargaPasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLCargaPasajero.setForeground(new java.awt.Color(51, 51, 51));
        jLCargaPasajero.setText("Carga de pasajero");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDNI)
                    .addComponent(jLNombre)
                    .addComponent(jLApellido)
                    .addComponent(jLCorreo)
                    .addComponent(jLTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTDNI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCargaPasajero)
                        .addGap(283, 283, 283))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLCargaPasajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDNI)
                    .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCorreo)
                    .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefono)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseEntered
        jBGuardar.setBackground(new Color(0, 102, 102));
        jBGuardar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBGuardarMouseEntered

    private void jBGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuardarMouseExited
        jBGuardar.setBackground(new Color(255, 255, 255));
        jBGuardar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jBGuardarMouseExited

    private void jBLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseEntered
        jBLimpiar.setBackground(new Color(0, 102, 102));
        jBLimpiar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBLimpiarMouseEntered

    private void jBLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiarMouseExited
        jBLimpiar.setBackground(new Color(255, 255, 255));
        jBLimpiar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jBLimpiarMouseExited

    private void jTDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDNIMousePressed
        if (jTDNI.getText().equals("Ingrese su DNI")) {
            jTDNI.setText("");
            jTDNI.setForeground(Color.BLACK);
        }
        if (jTNombre.getText().isEmpty()) {
            jTNombre.setText("Ingrese su nombre");
            jTNombre.setForeground(Color.GRAY);
        }
        if (jTApellido.getText().isEmpty()) {
            jTApellido.setText("Ingrese su apellido");
            jTApellido.setForeground(Color.GRAY);
        }
        if (jTCorreo.getText().isEmpty()) {
            jTCorreo.setText("Ingrese su correo electrónico");
            jTCorreo.setForeground(Color.GRAY);
        }
        if (jTTelefono.getText().isEmpty()) {
            jTTelefono.setText("Ingrese el numero de su telefono");
            jTTelefono.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_jTDNIMousePressed

    private void jTNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTNombreMousePressed
        if (jTNombre.getText().equals("Ingrese su nombre")) {
            jTNombre.setText("");
            jTNombre.setForeground(Color.BLACK);
        }
        if (jTDNI.getText().isEmpty()) {
            jTDNI.setText("Ingrese su DNI");
            jTDNI.setForeground(Color.GRAY);
        }
        if (jTApellido.getText().isEmpty()) {
            jTApellido.setText("Ingrese su apellido");
            jTApellido.setForeground(Color.GRAY);
        }
        if (jTCorreo.getText().isEmpty()) {
            jTCorreo.setText("Ingrese su correo electronico");
            jTCorreo.setForeground(Color.GRAY);
        }
        if (jTTelefono.getText().isEmpty()) {
            jTTelefono.setText("Ingrese el numero de su telefono");
            jTTelefono.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTNombreMousePressed

    private void jTApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTApellidoMousePressed
        if (jTApellido.getText().equals("Ingrese su apellido")) {
            jTApellido.setText("");
            jTApellido.setForeground(Color.BLACK);
        }
        if (jTDNI.getText().isEmpty()) {
            jTDNI.setText("Ingrese su DNI");
            jTDNI.setForeground(Color.GRAY);
        }
        if (jTNombre.getText().isEmpty()) {
            jTNombre.setText("Ingrese su nombre");
            jTNombre.setForeground(Color.GRAY);
        }
        if (jTCorreo.getText().isEmpty()) {
            jTCorreo.setText("Ingrese su correo electronico");
            jTCorreo.setForeground(Color.GRAY);
        }
        if (jTTelefono.getText().isEmpty()) {
            jTTelefono.setText("Ingrese el numero de su telefono");
            jTTelefono.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTApellidoMousePressed

    private void jTCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCorreoMousePressed
        if (jTCorreo.getText().equals("Ingrese su correo electronico")) {
            jTCorreo.setText("");
            jTCorreo.setForeground(Color.BLACK);
        }
        if (jTDNI.getText().isEmpty()) {
            jTDNI.setText("Ingrese su DNI");
            jTDNI.setForeground(Color.GRAY);
        }
        if (jTNombre.getText().isEmpty()) {
            jTNombre.setText("Ingrese su nombre");
            jTNombre.setForeground(Color.GRAY);
        }
        if (jTApellido.getText().isEmpty()) {
            jTApellido.setText("Ingrese su apellido");
            jTApellido.setForeground(Color.GRAY);
        }
        if (jTTelefono.getText().isEmpty()) {
            jTTelefono.setText("Ingrese el numero de su telefono");
            jTTelefono.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTCorreoMousePressed

    private void jTTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTelefonoMousePressed
        if (jTTelefono.getText().equals("Ingrese el numero de su telefono")) {
            jTTelefono.setText("");
            jTTelefono.setForeground(Color.BLACK);
        }
        if (jTDNI.getText().isEmpty()) {
            jTDNI.setText("Ingrese su DNI");
            jTDNI.setForeground(Color.GRAY);
        }
        if (jTNombre.getText().isEmpty()) {
            jTNombre.setText("Ingrese su nombre");
            jTNombre.setForeground(Color.GRAY);
        }
        if (jTApellido.getText().isEmpty()) {
            jTApellido.setText("Ingrese su apellido");
            jTApellido.setForeground(Color.GRAY);
        }
        if (jTCorreo.getText().isEmpty()) {
            jTCorreo.setText("Ingrese su correo electronico");
            jTCorreo.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTTelefonoMousePressed

    private void jTDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDNIKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter) && caracter != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jTDNIKeyTyped

    private void jTTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter) && caracter != '+'
             && caracter != '-' && caracter != '('
             && caracter != ')') {
            evt.consume();
        }
    }//GEN-LAST:event_jTTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCargaPasajero;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables
}
