package vistas.entregaFinal;

import EmpresaDeColectivo.Entidades.Colectivo;
import accesoADatos.ColectivoData;
import java.awt.Color;
import java.util.List;
import javax.swing.JComboBox;


public class CargaDeColectivos extends javax.swing.JPanel {
    
    public CargaDeColectivos() {
        initComponents();
        initCombos();
        comboMarca.setSelectedIndex(-1);
        comboModelo.setSelectedIndex(-1);
        jBActualizar.setEnabled(false);
    }
    
    public CargaDeColectivos(Colectivo colectivo){
        initComponents();
        initCombos();
        comboMarca.setSelectedItem(colectivo.getMarca());
        comboModelo.setSelectedItem(colectivo.getModelo());
        jBAgregar.setEnabled(false);
        jBActualizar.setEnabled(true);
        txtCapacidad.setText(Integer.toString(colectivo.getCapacidad()));
        txtMatricula.setText(colectivo.getMatricula());
        
        
    }
    
    private void setComboEditable(JComboBox combo){
        combo.setEditable(true);
        combo.addActionListener(e -> {
            String itemNuevo = (String) combo.getSelectedItem();
            if (itemNuevo != null && !itemNuevo.trim().isEmpty() && combo.getItemCount() == 0) {
                combo.addItem(itemNuevo);
            }
        });
    }
    
    private void initCombos(){
        ColectivoData colectivoData = new ColectivoData();
        List<String> marcas = colectivoData.listarMarcas();
        List<String> modelos = colectivoData.listarModelos();
        
        for(String marca : marcas){
            comboMarca.addItem(marca);
        }
        
        for(String modelo : modelos){
            comboModelo.addItem(modelo);
        }
        
        setComboEditable(comboMarca);
        setComboEditable(comboModelo);
    }
    
    private void limpiarCampos(){
        jBAgregar.setEnabled(true);
        jBActualizar.setEnabled(false);
        comboMarca.setSelectedIndex(-1);
        comboModelo.setSelectedIndex(-1);
        txtCapacidad.setText("");
        txtMatricula.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColectivo = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblDatosColectivo = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        comboModelo = new javax.swing.JComboBox<>();
        txtCapacidad = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBLimpieza = new javax.swing.JButton();
        lblModelo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelColectivo.setBackground(new java.awt.Color(255, 255, 255));
        panelColectivo.setForeground(new java.awt.Color(0, 204, 204));
        panelColectivo.setPreferredSize(new java.awt.Dimension(862, 240));

        lblMarca.setForeground(new java.awt.Color(102, 102, 102));
        lblMarca.setText("Marca");

        lblDatosColectivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDatosColectivo.setForeground(new java.awt.Color(51, 51, 51));
        lblDatosColectivo.setText("Cargar colectivos");

        lblMatricula.setForeground(new java.awt.Color(102, 102, 102));
        lblMatricula.setText("Matricula");

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setForeground(new java.awt.Color(102, 102, 102));
        txtMatricula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));

        lblCapacidad.setForeground(new java.awt.Color(102, 102, 102));
        lblCapacidad.setText("Capacidad");

        comboMarca.setBackground(new java.awt.Color(255, 255, 255));
        comboMarca.setForeground(new java.awt.Color(102, 102, 102));
        comboMarca.setSelectedIndex(-1);

        comboModelo.setBackground(new java.awt.Color(255, 255, 255));
        comboModelo.setForeground(new java.awt.Color(102, 102, 102));

        txtCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad.setForeground(new java.awt.Color(102, 102, 102));
        txtCapacidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });

        jBAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jBAgregar.setForeground(new java.awt.Color(102, 102, 102));
        jBAgregar.setText("Agregar");
        jBAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jBAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgregarMouseExited(evt);
            }
        });

        jBActualizar.setBackground(new java.awt.Color(255, 255, 255));
        jBActualizar.setForeground(new java.awt.Color(102, 102, 102));
        jBActualizar.setText("Actualizar");
        jBActualizar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jBActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBActualizarMouseExited(evt);
            }
        });

        jBLimpieza.setBackground(new java.awt.Color(255, 255, 255));
        jBLimpieza.setForeground(new java.awt.Color(102, 102, 102));
        jBLimpieza.setText("Limpiar");
        jBLimpieza.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        jBLimpieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBLimpiezaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBLimpiezaMouseExited(evt);
            }
        });
        jBLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiezaActionPerformed(evt);
            }
        });

        lblModelo.setForeground(new java.awt.Color(102, 102, 102));
        lblModelo.setText("Modelo");

        javax.swing.GroupLayout panelColectivoLayout = new javax.swing.GroupLayout(panelColectivo);
        panelColectivo.setLayout(panelColectivoLayout);
        panelColectivoLayout.setHorizontalGroup(
            panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColectivoLayout.createSequentialGroup()
                .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColectivoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelColectivoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelColectivoLayout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addGap(54, 54, 54)
                                .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addComponent(jBActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jBLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(panelColectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModelo)
                .addGap(290, 290, 290)
                .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelColectivoLayout.createSequentialGroup()
                        .addComponent(lblMatricula)
                        .addGap(46, 46, 46)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelColectivoLayout.createSequentialGroup()
                        .addComponent(lblCapacidad)
                        .addGap(40, 40, 40)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColectivoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDatosColectivo)
                .addGap(342, 342, 342))
        );
        panelColectivoLayout.setVerticalGroup(
            panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColectivoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDatosColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(comboMarca)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidad)
                    .addComponent(lblCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboModelo)
                    .addComponent(lblModelo))
                .addGap(45, 45, 45)
                .addGroup(panelColectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseEntered
        jBAgregar.setBackground(new Color(0, 102, 102));
        jBAgregar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBAgregarMouseEntered

    private void jBAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseExited
        jBAgregar.setBackground(new Color(255, 255, 255));
        jBAgregar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jBAgregarMouseExited

    private void jBActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseEntered
        jBActualizar.setBackground(new Color(0, 102, 102));
        jBActualizar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBActualizarMouseEntered

    private void jBActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBActualizarMouseExited
        jBActualizar.setBackground(new Color(255, 255, 255));
        jBActualizar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jBActualizarMouseExited

    private void jBLimpiezaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiezaMouseEntered
        jBLimpieza.setBackground(new Color(0, 102, 102));
        jBLimpieza.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jBLimpiezaMouseEntered

    private void jBLimpiezaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimpiezaMouseExited
        jBLimpieza.setBackground(new Color(255, 255, 255));
        jBLimpieza.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jBLimpiezaMouseExited

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCapacidadKeyTyped

    private void jBLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiezaActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBLimpiezaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBLimpieza;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblDatosColectivo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JPanel panelColectivo;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
